"""Configuration settings for StockTrendAI application"""

# Indian Stock Symbols (NSE, BSE & All Indian Exchanges - Complete List)
# This comprehensive list includes large-cap, mid-cap, small-cap companies from all major Indian exchanges
# Total companies: 437+ covering all sectors and market segments
INDIAN_STOCKS = {
    'AARTIDRUGS': 'Aarti Drugs Ltd',
    'AARTIIND': 'Aarti Industries Ltd',
    'AARTIPHARM': 'Aarti Pharmalabs Ltd',
    'AAVAS': 'Aavas Financiers Ltd',
    'ABBOTINDIA': 'Abbott India Ltd',
    'ACC': 'ACC Ltd',
    'ACCELYA': 'Accelya Solutions India Ltd',
    'ACLGATI': 'Allcargo Gati Ltd',
    'ADANIENT': 'Adani Enterprises Ltd',
    'ADANIGAS': 'Adani Gas Ltd',
    'ADANIGREEN': 'Adani Green Energy Ltd',
    'ADANIPORTS': 'Adani Ports and Special Economic Zone Ltd',
    'ADANIPOWER': 'Adani Power Ltd',
    'ADANITRANS': 'Adani Transmission Ltd',
    'ADF': 'ADF Foods Ltd',
    'AEGISLOG': 'Aegis Logistics Ltd',
    'AFFLE': 'Affle India Ltd',
    'AHLUWALIA': 'Ahluwalia Contracts India Ltd',
    'AIAENG': 'AIA Engineering Ltd',
    'AJANTPHARM': 'Ajanta Pharma Ltd',
    'AKUMS': 'Akums Drugs & Pharmaceuticals Ltd',
    'AKZOINDIA': 'Akzo Nobel India Ltd',
    'ALANKIT': 'Alankit Ltd',
    'ALIVUS': 'Alivus Life Sciences Ltd',
    'ALKEM': 'Alkem Laboratories Ltd',
    'ALKYLAMINE': 'Alkyl Amines Chemicals Ltd',
    'ALLCARGO': 'Allcargo Logistics Ltd',
    'ALMONDZ': 'Almondz Global Securities Ltd',
    'ALPA': 'Alpa Laboratories Ltd',
    'ALPHAGEO': 'Alphageo India Ltd',
    'AMARAJABAT': 'Amara Raja Energy & Mobility Ltd',
    'AMARJOTHI': 'Amarjothi Spinning Mills Ltd',
    'AMBER': 'Amber Enterprises India Ltd',
    'AMBUJACEM': 'Ambuja Cements Ltd',
    'AMNPLST': 'Amines & Plasticizers Ltd',
    'ANGELONE': 'Angel One Ltd',
    'ANURAS': 'Anupam Rasayan India Ltd',
    'APCOTEXIND': 'Apcotex Industries Ltd',
    'APLAPOLLO': 'APL Apollo Tubes Ltd',
    'APOLLOHOSP': 'Apollo Hospitals Enterprise Ltd',
    'APOLLOTYRE': 'Apollo Tyres Ltd',
    'APOLSINHOT': 'Apollo Sindoori Hotels Ltd',
    'ARVIND': 'Arvind Ltd',
    'ARVINDFASN': 'Arvind Fashions Ltd',
    'ASHOKA': 'Ashoka Buildcon Ltd',
    'ASHOKLEY': 'Ashok Leyland Ltd',
    'ASIANPAINT': 'Asian Paints Ltd',
    'ASTERDM': 'Aster DM Healthcare Ltd',
    'ASTRAL': 'Astral Ltd',
    'ASTRAZEN': 'AstraZeneca Pharma India Ltd',
    'ATGL': 'Adani Total Gas Ltd',
    'ATUL': 'Atul Ltd',
    'AUBANK': 'AU Small Finance Bank Ltd',
    'AUROPHARMA': 'Aurobindo Pharma Ltd',
    'AVANTIFEED': 'Avanti Feeds Ltd',
    'AXISBANK': 'Axis Bank Ltd',
    'BAJAJ-AUTO': 'Bajaj Auto Ltd',
    'BAJAJCON': 'Bajaj Consumer Care Ltd',
    'BAJAJFINSV': 'Bajaj Finserv Ltd',
    'BAJFINANCE': 'Bajaj Finance Ltd',
    'BALAJITELE': 'Balaji Telefilms Ltd',
    'BALKRISIND': 'Balkrishna Industries Ltd',
    'BALRAMCHIN': 'Balrampur Chini Mills Ltd',
    'BANDHANBNK': 'Bandhan Bank Ltd',
    'BANKINDIA': 'Bank of India',
    'BANKBARODA': 'Bank of Baroda',
    'BASF': 'BASF India Ltd',
    'BATAINDIA': 'Bata India Ltd',
    'BEL': 'Bharat Electronics Ltd',
    'BEML': 'BEML Ltd',
    'BERGEPAINT': 'Berger Paints India Ltd',
    'BHARATFORG': 'Bharat Forge Ltd',
    'BHARATRAS': 'Bharat Rasayan Ltd',
    'BHARTIARTL': 'Bharti Airtel Ltd',
    'BHARTIHEXA': 'Bharti Hexacom Ltd',
    'BHEL': 'Bharat Heavy Electricals Ltd',
    'BIOCON': 'Biocon Ltd',
    'BLISSGVS': 'Bliss GVS Pharma Ltd',
    'BLUESTARCO': 'Blue Star Ltd',
    'BOMDYEING': 'Bombay Dyeing & Manufacturing Company Ltd',
    'BOSCHLTD': 'Bosch Ltd',
    'BPCL': 'Bharat Petroleum Corporation Ltd',
    'BRIGADE': 'Brigade Enterprises Ltd',
    'BRITANNIA': 'Britannia Industries Ltd',
    'BSOFT': 'Birlasoft Ltd',
    'CADILAHC': 'Cadila Healthcare Ltd',
    'CANBK': 'Canara Bank',
    'CANFINHOME': 'Can Fin Homes Ltd',
    'CAPLIPOINT': 'Caplin Point Laboratories Ltd',
    'CARBORUNIV': 'Carborundum Universal Ltd',
    'CARERATING': 'Care Ratings Ltd',
    'CASTROLIND': 'Castrol India Ltd',
    'CCL': 'CCL Products India Ltd',
    'CEATLTD': 'CEAT Ltd',
    'CENTRALBK': 'Central Bank of India',
    'CENTURYTEX': 'Century Textiles and Industries Ltd',
    'CERA': 'Cera Sanitaryware Ltd',
    'CESC': 'CESC Ltd',
    'CHAMBLFERT': 'Chambal Fertilizers and Chemicals Ltd',
    'CHENNPETRO': 'Chennai Petroleum Corporation Ltd',
    'CHOLAFIN': 'Cholamandalam Investment and Finance Company Ltd',
    'CHOLAHLDNG': 'Cholamandalam Financial Holdings Ltd',
    'CIPLA': 'Cipla Ltd',
    'CLEAN': 'Clean Science and Technology Ltd',
    'COALINDIA': 'Coal India Ltd',
    'COFORGE': 'Coforge Ltd',
    'COLPAL': 'Colgate Palmolive India Ltd',
    'CONCOR': 'Container Corporation of India Ltd',
    'COROMANDEL': 'Coromandel International Ltd',
    'CREDITACC': 'Credit Access Grameen Ltd',
    'CROMPTON': 'Crompton Greaves Consumer Electricals Ltd',
    'CUB': 'City Union Bank Ltd',
    'CUMMINSIND': 'Cummins India Ltd',
    'CYIENT': 'Cyient Ltd',
    'DABUR': 'Dabur India Ltd',
    'DALBHARAT': 'Dalmia Bharat Ltd',
    'DBCORP': 'D.B. Corp Ltd',
    'DCBBANK': 'DCB Bank Ltd',
    'DEEPAKNTR': 'Deepak Nitrite Ltd',
    'DELTACORP': 'Delta Corp Ltd',
    'DHFL': 'Dewan Housing Finance Corporation Ltd',
    'DISHTV': 'Dish TV India Ltd',
    'DIVISLAB': 'Divis Laboratories Ltd',
    'DIXON': 'Dixon Technologies India Ltd',
    'DLF': 'DLF Ltd',
    'DMART': 'Avenue Supermarts Ltd',
    'DOLLAR': 'Dollar Industries Ltd',
    'DRREDDY': 'Dr. Reddys Laboratories Ltd',
    'EDELWEISS': 'Edelweiss Financial Services Ltd',
    'EICHERMOT': 'Eicher Motors Ltd',
    'EIDPARRY': 'EID Parry India Ltd',
    'EIHOTEL': 'EIH Ltd',
    'EMAMILTD': 'Emami Ltd',
    'ENDURANCE': 'Endurance Technologies Ltd',
    'ENIL': 'Entertainment Network India Ltd',
    'EQUITAS': 'Equitas Small Finance Bank Ltd',
    'EQUITASBNK': 'Equitas Small Finance Bank Ltd',
    'ERIS': 'Eris Lifesciences Ltd',
    'ESCORTS': 'Escorts Kubota Ltd',
    'EXIDEIND': 'Exide Industries Ltd',
    'FEDERALBNK': 'Federal Bank Ltd',
    'FINEORG': 'Fine Organic Industries Ltd',
    'FINPIPE': 'Finolex Industries Ltd',
    'FLUOROCHEM': 'Gujarat Fluorochemicals Ltd',
    'FORCEMOT': 'Force Motors Ltd',
    'FORTIS': 'Fortis Healthcare Ltd',
    'FSL': 'Firstsource Solutions Ltd',
    'GAIL': 'GAIL India Ltd',
    'GALAXYSURF': 'Galaxy Surfactants Ltd',
    'GARFIBRES': 'Garware Technical Fibres Ltd',
    'GESHIP': 'The Great Eastern Shipping Company Ltd',
    'GET&D': 'GE T&D India Ltd',
    'GILLETTE': 'Gillette India Ltd',
    'GLAND': 'Gland Pharma Ltd',
    'GLAXO': 'GlaxoSmithKline Pharmaceuticals Ltd',
    'GLENMARK': 'Glenmark Pharmaceuticals Ltd',
    'GMRINFRA': 'GMR Infrastructure Ltd',
    'GNFC': 'Gujarat Narmada Valley Fertilizers and Chemicals Ltd',
    'GODFRYPHLP': 'Godfrey Phillips India Ltd',
    'GODREJAGRO': 'Godrej Agrovet Ltd',
    'GODREJCP': 'Godrej Consumer Products Ltd',
    'GODREJIND': 'Godrej Industries Ltd',
    'GODREJPROP': 'Godrej Properties Ltd',
    'GPPL': 'Gujarat Pipavav Port Ltd',
    'GRANULES': 'Granules India Ltd',
    'GRAPHITE': 'Graphite India Ltd',
    'GRASIM': 'Grasim Industries Ltd',
    'GREAVESCOT': 'Greaves Cotton Ltd',
    'GRINDWELL': 'Grindwell Norton Ltd',
    'GSFC': 'Gujarat State Fertilizers and Chemicals Ltd',
    'GSPL': 'Gujarat State Petronet Ltd',
    'GTLINFRA': 'GTL Infrastructure Ltd',
    'GUJALKALI': 'Gujarat Alkalies and Chemicals Ltd',
    'GUJGASLTD': 'Gujarat Gas Ltd',
    'GULFOILLUB': 'Gulf Oil Lubricants India Ltd',
    'HAL': 'Hindustan Aeronautics Ltd',
    'HAPPSTMNDS': 'Happiest Minds Technologies Ltd',
    'HATHWAY': 'Hathway Cable & Datacom Ltd',
    'HATSUN': 'Hatsun Agro Product Ltd',
    'HAVELLS': 'Havells India Ltd',
    'HCC': 'Hindustan Construction Company Ltd',
    'HCLTECH': 'HCL Technologies Ltd',
    'HDFCAMC': 'HDFC Asset Management Company Ltd',
    'HDFCBANK': 'HDFC Bank Ltd',
    'HDFCLIFE': 'HDFC Life Insurance Company Ltd',
    'HEIDELBERG': 'HeidelbergCement India Ltd',
    'HERITAGE': 'Heritage Foods Ltd',
    'HEROMOTOCO': 'Hero MotoCorp Ltd',
    'HEXAWARE': 'Hexaware Technologies Ltd',
    'HFCL': 'HFCL Ltd',
    'HIMATSEIDE': 'Himatsingka Seide Ltd',
    'HINDALCO': 'Hindalco Industries Ltd',
    'HINDCOPPER': 'Hindustan Copper Ltd',
    'HINDPETRO': 'Hindustan Petroleum Corporation Ltd',
    'HINDUNILVR': 'Hindustan Unilever Ltd',
    'HINDZINC': 'Hindustan Zinc Ltd',
    'HONAUT': 'Honeywell Automation India Ltd',
    'HUDCO': 'Housing and Urban Development Corporation Ltd',
    'IBREALEST': 'Indiabulls Real Estate Ltd',
    'IBULHSGFIN': 'Indiabulls Housing Finance Ltd',
    'ICICIBANK': 'ICICI Bank Ltd',
    'ICICIGI': 'ICICI Lombard General Insurance Company Ltd',
    'ICICIPRULI': 'ICICI Prudential Life Insurance Company Ltd',
    'IDBI': 'IDBI Bank Ltd',
    'IDEA': 'Vodafone Idea Ltd',
    'IDFCFIRSTB': 'IDFC First Bank Ltd',
    'IEX': 'Indian Energy Exchange Ltd',
    'IFCI': 'Indian Financial Technology and Allied Services Ltd',
    'IGL': 'Indraprastha Gas Ltd',
    'IIFL': 'IIFL Finance Ltd',
    'INDIACEM': 'The India Cements Ltd',
    'INDIAMART': 'IndiaMART InterMESH Ltd',
    'INDIANB': 'Indian Bank',
    'INDHOTEL': 'The Indian Hotels Company Ltd',
    'INDIGO': 'InterGlobe Aviation Ltd',
    'INDOCO': 'Indoco Remedies Ltd',
    'INDORAMA': 'Indo Rama Synthetics India Ltd',
    'INDUSTOWER': 'Indus Towers Ltd',
    'INDUSINDBK': 'IndusInd Bank Ltd',
    'INFY': 'Infosys Ltd',
    'INOXLEISUR': 'INOX Leisure Ltd',
    'IOC': 'Indian Oil Corporation Ltd',
    'IOLCP': 'IOL Chemicals and Pharmaceuticals Ltd',
    'IRB': 'IRB Infrastructure Developers Ltd',
    'IRCTC': 'Indian Railway Catering And Tourism Corporation Ltd',
    'ISEC': 'ICICI Securities Ltd',
    'ITC': 'ITC Ltd',
    'ITI': 'ITI Ltd',
    'JAGRAN': 'Jagran Prakashan Ltd',
    'JAMNAAUTO': 'Jamna Auto Industries Ltd',
    'JARDANPIPE': 'Jardine Matheson Holdings Ltd',
    'JBCHEPHARM': 'JB Chemicals & Pharmaceuticals Ltd',
    'JINDALSTEL': 'Jindal Steel & Power Ltd',
    'JKCEMENT': 'JK Cement Ltd',
    'JKLAKSHMI': 'JK Lakshmi Cement Ltd',
    'JKPAPER': 'JK Paper Ltd',
    'JMFINANCIL': 'JM Financial Ltd',
    'JPASSOCIAT': 'Jaiprakash Associates Ltd',
    'JSL': 'Jindal Stainless Ltd',
    'JSWENERGY': 'JSW Energy Ltd',
    'JSWSTEEL': 'JSW Steel Ltd',
    'JUBLFOOD': 'Jubilant Foodworks Ltd',
    'JUSTDIAL': 'Just Dial Ltd',
    'JYOTHYLAB': 'Jyothy Labs Ltd',
    'KAJARIACER': 'Kajaria Ceramics Ltd',
    'KALPATPOWR': 'Kalpataru Power Transmission Ltd',
    'KALYANIJEW': 'Kalyani Forge Ltd',
    'KANSAINER': 'Kansai Nerolac Paints Ltd',
    'KEC': 'KEC International Ltd',
    'KEI': 'KEI Industries Ltd',
    'KNR': 'KNR Constructions Ltd',
    'KOTAKBANK': 'Kotak Mahindra Bank Ltd',
    'KPITTECH': 'KPIT Technologies Ltd',
    'KRBL': 'KRBL Ltd',
    'L&TFH': 'L&T Finance Holdings Ltd',
    'LALPATHLAB': 'Dr. Lal Pathlabs Ltd',
    'LAURUSLABS': 'Laurus Labs Ltd',
    'LAXMIMACH': 'Lakshmi Machine Works Ltd',
    'LEMONTREE': 'Lemon Tree Hotels Ltd',
    'LICHSGFIN': 'LIC Housing Finance Ltd',
    'LICI': 'Life Insurance Corporation of India',
    'LTIM': 'LTIMindtree Ltd',
    'LTTS': 'L&T Technology Services Ltd',
    'LUPIN': 'Lupin Ltd',
    'LUXIND': 'Lux Industries Ltd',
    'M&M': 'Mahindra & Mahindra Ltd',
    'MAHINDCIE': 'Mahindra CIE Automotive Ltd',
    'MAHLIFE': 'Mahindra Lifespace Developers Ltd',
    'MANAPPURAM': 'Manappuram Finance Ltd',
    'MARICO': 'Marico Ltd',
    'MARUTI': 'Maruti Suzuki India Ltd',
    'MASFIN': 'MAS Financial Services Ltd',
    'MAXHEALTH': 'Max Healthcare Institute Ltd',
    'MCDOWELL-N': 'McDowell Holdings Ltd',
    'MCX': 'Multi Commodity Exchange of India Ltd',
    'METROPOLIS': 'Metropolis Healthcare Ltd',
    'MGL': 'Mahanagar Gas Ltd',
    'MINDACORP': 'Minda Corporation Ltd',
    'MINDTECK': 'Mindteck India Ltd',
    'MINDTREE': 'Mindtree Ltd',
    'MMTC': 'MMTC Ltd',
    'MOIL': 'MOIL Ltd',
    'MOTHERSON': 'Motherson Sumi Wiring India Ltd',
    'MPHASIS': 'Mphasis Ltd',
    'MRF': 'MRF Ltd',
    'MRPL': 'Mangalore Refinery and Petrochemicals Ltd',
    'MUTHOOTFIN': 'Muthoot Finance Ltd',
    'NATIONALUM': 'National Aluminium Company Ltd',
    'NATCOPHAR': 'Natco Pharma Ltd',
    'NAUKRI': 'Info Edge India Ltd',
    'NAVINFLUOR': 'Navin Fluorine International Ltd',
    'NCC': 'NCC Ltd',
    'NESTLEIND': 'Nestle India Ltd',
    'NETWORK18': 'Network18 Media & Investments Ltd',
    'NEWGEN': 'Newgen Software Technologies Ltd',
    'NHPC': 'NHPC Ltd',
    'NIITLTD': 'NIIT Ltd',
    'NIITTECH': 'NIIT Technologies Ltd',
    'NMDC': 'NMDC Ltd',
    'NOCIL': 'NOCIL Ltd',
    'NTPC': 'NTPC Ltd',
    'NUVOCO': 'Nuvoco Vistas Corporation Ltd',
    'OBEROIRLTY': 'Oberoi Realty Ltd',
    'OFSS': 'Oracle Financial Services Software Ltd',
    'ONGC': 'Oil & Natural Gas Corporation Ltd',
    'ONMOBILE': 'OnMobile Global Ltd',
    'OPTIEMUS': 'Optiemus Infracom Ltd',
    'ORIENTCEM': 'Orient Cement Ltd',
    'ORIENTELEC': 'Orient Electric Ltd',
    'PAGEIND': 'Page Industries Ltd',
    'PARABDRUGS': 'Parabolic Drugs Ltd',
    'PAYTM': 'One 97 Communications Ltd',
    'PEL': 'Piramal Enterprises Ltd',
    'PERSISTENT': 'Persistent Systems Ltd',
    'PETRONET': 'Petronet LNG Ltd',
    'PFC': 'Power Finance Corporation Ltd',
    'PFIZER': 'Pfizer Ltd',
    'PGHH': 'Procter & Gamble Hygiene and Health Care Ltd',
    'PHOENIXLTD': 'The Phoenix Mills Ltd',
    'PIDILITIND': 'Pidilite Industries Ltd',
    'PIIND': 'PI Industries Ltd',
    'PNB': 'Punjab National Bank',
    'PNBHOUSING': 'PNB Housing Finance Ltd',
    'POLICYBZR': 'PB Fintech Ltd',
    'POLYCAB': 'Polycab India Ltd',
    'POWERGRID': 'Power Grid Corporation of India Ltd',
    'POWERINDIA': 'ABB Power Products and Systems India Ltd',
    'PRAJIND': 'Praj Industries Ltd',
    'PRESTIGE': 'Prestige Estates Projects Ltd',
    'PRISM': 'Prism Johnson Ltd',
    'PRSMJOHNSN': 'Prism Johnson Ltd',
    'PUNJLLOYD': 'Punj Lloyd Ltd',
    'PURAVANKARA': 'Puravankara Ltd',
    'PVR': 'PVR Ltd',
    'PVRINOX': 'PVR INOX Ltd',
    'QUESS': 'Quess Corp Ltd',
    'RADICO': 'Radico Khaitan Ltd',
    'RAIN': 'Rain Industries Ltd',
    'RAJESHEXPO': 'Rajesh Exports Ltd',
    'RALLIS': 'Rallis India Ltd',
    'RAMCOCEM': 'The Ramco Cements Ltd',
    'RAMSARUP': 'Ramsarup Industries Ltd',
    'RATNAMANI': 'Ratnamani Metals & Tubes Ltd',
    'RAYMOND': 'Raymond Ltd',
    'RBLBANK': 'RBL Bank Ltd',
    'RCF': 'Rashtriya Chemicals and Fertilizers Ltd',
    'RCOM': 'Reliance Communications Ltd',
    'RECLTD': 'REC Ltd',
    'REDINGTON': 'Redington Ltd',
    'RELIANCE': 'Reliance Industries Ltd',
    'RELINFRA': 'Reliance Infrastructure Ltd',
    'RELAXO': 'Relaxo Footwears Ltd',
    'RPOWER': 'Reliance Power Ltd',
    'RSWM': 'RSWM Ltd',
    'SADBHAV': 'Sadbhav Engineering Ltd',
    'SAIL': 'Steel Authority of India Ltd',
    'SAREGAMA': 'Saregama India Ltd',
    'SBIN': 'State Bank of India',
    'SCHAEFFLER': 'Schaeffler India Ltd',
    'SEQUENT': 'Sequent Scientific Ltd',
    'SFL': 'Sheela Foam Ltd',
    'SHILPAMED': 'Shilpa Medicare Ltd',
    'SHOPERSTOP': 'Shoppers Stop Ltd',
    'SHREECEM': 'Shree Cement Ltd',
    'SHRIRAMFIN': 'Shriram Finance Ltd',
    'SIEMENS': 'Siemens Ltd',
    'SOBHA': 'Sobha Ltd',
    'SONACOMS': 'Sona BLW Precision Forgings Ltd',
    'SONATSOFTW': 'Sonata Software Ltd',
    'SPARC': 'Sun Pharma Advanced Research Company Ltd',
    'SRF': 'SRF Ltd',
    'STAR': 'Strides Pharma Science Ltd',
    'STARCEMENT': 'Star Cement Ltd',
    'STRIDES': 'Strides Pharma Science Ltd',
    'SUBEX': 'Subex Ltd',
    'SUDARSCHEM': 'Sudarshan Chemical Industries Ltd',
    'SUNDRMFAST': 'Sundram Fasteners Ltd',
    'SUNPHARMA': 'Sun Pharmaceutical Industries Ltd',
    'SUNTV': 'Sun TV Network Ltd',
    'SUVEN': 'Suven Life Sciences Ltd',
    'SUTLEJTEX': 'Sutlej Textiles and Industries Ltd',
    'SYMPHONY': 'Symphony Ltd',
    'TATACHEM': 'Tata Chemicals Ltd',
    'TATACOMM': 'Tata Communications Ltd',
    'TATACONSUM': 'Tata Consumer Products Ltd',
    'TATAELXSI': 'Tata Elxsi Ltd',
    'TATAINVEST': 'Tata Investment Corporation Ltd',
    'TATAMOTORS': 'Tata Motors Ltd',
    'TATAPOWER': 'Tata Power Company Ltd',
    'TATASTEEL': 'Tata Steel Ltd',
    'TATATECH': 'Tata Technologies Ltd',
    'TCS': 'Tata Consultancy Services Ltd',
    'TEAMLEASE': 'TeamLease Services Ltd',
    'TECHM': 'Tech Mahindra Ltd',
    'TEJAS': 'Tejas Networks Ltd',
    'THERMAX': 'Thermax Ltd',
    'TIINDIA': 'Tube Investments of India Ltd',
    'TIMKEN': 'Timken India Ltd',
    'TITAN': 'Titan Company Ltd',
    'TORNTPHARM': 'Torrent Pharmaceuticals Ltd',
    'TORNTPOWER': 'Torrent Power Ltd',
    'TRENT': 'Trent Ltd',
    'TRITURBINE': 'Triveni Turbine Ltd',
    'TTKPRESTIG': 'TTK Prestige Ltd',
    'TV18BRDCST': 'TV18 Broadcast Ltd',
    'TVSMOTOR': 'TVS Motor Company Ltd',
    'UBL': 'United Breweries Ltd',
    'UJJIVAN': 'Ujjivan Financial Services Ltd',
    'UJJIVANSFB': 'Ujjivan Small Finance Bank Ltd',
    'ULTRACEMCO': 'UltraTech Cement Ltd',
    'UNIONBANK': 'Union Bank of India',
    'UPL': 'UPL Ltd',
    'USHAMART': 'Usha Martin Ltd',
    'VAIBHAVGBL': 'Vaibhav Global Ltd',
    'VARDHACRLC': 'Vardhman Textiles Ltd',
    'VARROC': 'Varroc Engineering Ltd',
    'VBL': 'Varun Beverages Ltd',
    'VEDL': 'Vedanta Ltd',
    'VENKEYS': 'Venky\'s India Ltd',
    'VGUARD': 'V-Guard Industries Ltd',
    'VINATIORGA': 'Vinati Organics Ltd',
    'VIPIND': 'VIP Industries Ltd',
    'VOLTAS': 'Voltas Ltd',
    'VSTIND': 'VST Industries Ltd',
    'WABCOINDIA': 'Wabco India Ltd',
    'WELCORP': 'Welspun Corp Ltd',
    'WELSPUNIND': 'Welspun India Ltd',
    'WESTLIFE': 'Westlife Development Ltd',
    'WHIRLPOOL': 'Whirlpool of India Ltd',
    'WIPRO': 'Wipro Ltd',
    'WOCKPHARMA': 'Wockhardt Ltd',
    'YESBANK': 'Yes Bank Ltd',
    'ZEEL': 'Zee Entertainment Enterprises Ltd',
    'ZENSARTECH': 'Zensar Technologies Ltd',
    'ZENTEC': 'Zen Technologies Ltd',
    'ZOMATO': 'Zomato Ltd',
}

# Indian Market Indices (Valid Yahoo Finance symbols)
INDIAN_INDICES = {
    'NIFTYBEES.NS': 'NIFTY 50 ETF',
    'BANKBEES.NS': 'BANK NIFTY ETF',
    'ITBEES.NS': 'IT SECTOR ETF',
    'JUNIORBEES.NS': 'JUNIOR NIFTY ETF',
    'GOLDBEES.NS': 'GOLD ETF',
    'LIQUIDBEES.NS': 'LIQUID ETF',
    'PSUBNKBEES.NS': 'PSU BANK ETF',
    'CPSEETF.NS': 'CPSE ETF'
}

# Default stock to load on startup
DEFAULT_STOCK = 'RELIANCE'

# Model Configuration
MODEL_CONFIG = {
    'xgboost': {
        'n_estimators': 100,
        'max_depth': 10,
        'min_samples_split': 5,
        'min_samples_leaf': 2,
        'random_state': 42
    },
    'lstm': {
        'sequence_length': 60,
        'epochs': 50,
        'batch_size': 32,
        'validation_split': 0.2
    }
}

# Technical Indicators Configuration
TECHNICAL_INDICATORS = {
    'sma_periods': [20, 50],
    'ema_periods': [20],
    'rsi_period': 14,
    'macd_fast': 12,
    'macd_slow': 26,
    'macd_signal': 9,
    'bollinger_period': 20,
    'bollinger_std': 2,
    'stochastic_k': 14,
    'stochastic_d': 3,
    'williams_r_period': 14,
    'atr_period': 14,
    'volatility_period': 20,
    'momentum_period': 10,
    'roc_period': 12,
    'cci_period': 20
}

# Data Configuration
DATA_CONFIG = {
    'default_period': '1y',
    'available_periods': ['5m', '15m', '30m', '1h', '1d', '5d', '1mo', '3mo', '6mo', '1y', '2y', '5y', '10y', 'max'],
    'default_interval': '1d',
    'cache_duration': 300,  # 5 minutes in seconds for historical data
    'realtime_cache_duration': 60,  # 1 minute cache for real-time data
    'max_retries': 3,
    'timeout': 30,
    'period_intervals': {
        '5m': '1m',
        '15m': '5m', 
        '30m': '15m',
        '1h': '30m',
        '1d': '1h',
        '5d': '1d',
        '1mo': '1d',
        '3mo': '1d',
        '6mo': '1d',
        '1y': '1d',
        '2y': '1d',
        '5y': '1d',
        '10y': '1d',
        'max': '1d'
    }
}

# UI Configuration
UI_CONFIG = {
    'auto_refresh_interval': 30,  # seconds
    'prediction_card_animation': True,
    'chart_height': 800,
    'neon_glow_enabled': True,
    'mobile_responsive': True
}

# Market Configuration
MARKET_CONFIG = {
    'trading_hours': {
        'start': '09:15',
        'end': '15:30'
    },
    'timezone': 'Asia/Kolkata',
    'market_days': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    'holidays': []  # Can be populated with Indian market holidays
}

# Risk Management
RISK_CONFIG = {
    'max_position_size': 0.1,  # 10% of portfolio
    'stop_loss': 0.05,  # 5% stop loss
    'take_profit': 0.15,  # 15% take profit
    'risk_free_rate': 0.06,  # 6% annual risk-free rate
    'max_drawdown_threshold': 0.2  # 20% maximum drawdown
}

# API Configuration
API_CONFIG = {
    'yahoo_finance': {
        'base_url': 'https://query1.finance.yahoo.com',
        'timeout': 30,
        'max_retries': 3
    },
    'rate_limits': {
        'requests_per_minute': 60,
        'requests_per_hour': 1000
    }
}

# Logging Configuration
LOGGING_CONFIG = {
    'level': 'INFO',
    'format': '%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    'file_path': 'logs/stocktrendai.log',
    'max_file_size': 10485760,  # 10MB
    'backup_count': 5
}

# Performance Thresholds
PERFORMANCE_THRESHOLDS = {
    'minimum_accuracy': 0.55,  # 55% minimum accuracy
    'confidence_threshold': 0.6,  # 60% minimum confidence
    'data_freshness': 3600,  # 1 hour maximum data age
    'model_retrain_threshold': 0.05  # Retrain if accuracy drops by 5%
}

# Feature Engineering
FEATURE_CONFIG = {
    'technical_indicators': True,
    'price_ratios': True,
    'volume_analysis': True,
    'volatility_measures': True,
    'momentum_indicators': True,
    'trend_indicators': True,
    'oscillators': True
}

# Prediction Configuration
PREDICTION_CONFIG = {
    'ensemble_weights': {
        'xgboost': 0.6,
        'lstm': 0.4
    },
    'confidence_adjustment': {
        'volatility_factor': 0.8,
        'trend_factor': 1.2,
        'volume_factor': 1.1
    },
    'prediction_horizon': 1,  # Days
    'update_frequency': 'daily'
}

# Backtesting Configuration
BACKTEST_CONFIG = {
    'initial_capital': 100000,  # INR 1 Lakh
    'commission': 0.001,  # 0.1% commission
    'slippage': 0.0005,  # 0.05% slippage
    'min_periods': 252,  # Minimum 1 year of data
    'benchmark': '^NSEI'  # NIFTY 50 as benchmark
}

# Alert Configuration
ALERT_CONFIG = {
    'price_change_threshold': 0.05,  # 5% price change
    'volume_spike_threshold': 2.0,  # 2x average volume
    'rsi_overbought': 70,
    'rsi_oversold': 30,
    'volatility_spike_threshold': 1.5  # 1.5x average volatility
}

# Model Persistence
MODEL_PERSISTENCE = {
    'save_interval': 'daily',
    'max_model_age': 30,  # days
    'backup_models': True,
    'compression': True,
    'encryption': False
}
